name: smart_data_hub_test
channels:
  - pypi
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip:
    - dash==2.17.1
    - gempy==2024.2.0.2
    - gempy-viewer==2024.2.0
    - pandas==2.2.2
    - pyvista==0.43.10
    - pyyaml==6.0.1