gui_title: URS-data-Hub
logo_data_hub_png: URSLogoV1.png
logo_data_hub_png_title: Data Hub Logo
# additional logo on top right
logo_png:
uni_logo_png: rwth_mbd_en_rgb.png
main_dropdown_title: 'Host rock:'